### ISSUE TITLE
Huge numbers give NaN0000 over and over when using .toString()

### ISSUE THREAD

**Issue by Numbermaniac** [peterolson/BigInteger.js#70] opened 2016-01-21 02:02 UTC
For example, if you do something like this:

var a = bigInt(2).pow(1000000).minus(1);
document.write(a.toString());

The printed result is:

http://pastebin.com/PBks4FPu

If you go towards the bottom there's actual numbers, but it starts off with that mess. What's going on here?

**Comment by peterolson** [comment] 2016-01-27 01:49
Thanks for the bug report. This was caused by a bug in the Karatsuba multiplication function. It should be fixed now.

**Closed by peterolson** 2016-01-27 01:49 UTC
